       78 ID-RESOURCE    VALUE 1.

       78 IDM-FILE       VALUE 1.
       78 IDM-TOPEXIT    VALUE 2.
       78 IDM-HELP       VALUE 3.

       78 IDM-READ       VALUE 10.
       78 IDM-DELETE     VALUE 11.
       78 IDM-WRITE      VALUE 12.
       78 IDM-REWRITE    VALUE 13.
       78 IDM-PREVIOUS   VALUE 14.
       78 IDM-NEXT       VALUE 15.
       78 IDM-CLEAR      VALUE 16.

       78 IDM-EXIT       VALUE 40.
       78 IDM-RESUME     VALUE 41.
