/*------------------------
   PMNEWUP.H header file
  ------------------------*/

#define ID_RESOURCE      1

#define IDM_FILE         1    // Top-level items
#define IDM_TOPEXIT      2
#define IDM_HELP         3

#define IDM_READ         10   // "File" submenu
#define IDM_DELETE       11
#define IDM_WRITE        12
#define IDM_REWRITE      13
#define IDM_PREVIOUS     14
#define IDM_NEXT         15
#define IDM_CLEAR        16

#define IDM_EXIT         40   // "Exit" submenu
#define IDM_RESUME       41
